---
kind: pipeline
type: docker
name: njtech-mc-frontend

steps:
  - name: restore-build-cache
    image: drillster/drone-volume-cache:latest
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./target
  - name: build
    image: rustlang/rust:nightly
    commands:
      - cargo build --release
  - name: publish
    image: plugins/docker:latest
    settings:
      dockerfile: Dockerfile
      tag:
        - latest
        - ${DRONE_BUILD_NUMBER}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: https://harbor.jinhun.moe
      repo: harbor.jinhun.moe/library/njtech-mc-backend
  - name: rebuild-build-cache
    image: drillster/drone-volume-cache:latest
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./target
  - name: deploy
    image: harbor.jinhun.moe/library/depoly:latest
    settings:
      host:
        from_secret: deploy_host
      username: 
        from_secret: deploy_username
      key:
        from_secret: deploy_key
      script:
        from_secret: deploy_script

volumes:
  - name: cache
    host:
      path: /tmp/cache

image_pull_secrets:
  - dockerconfig

---
kind: signature
hmac: f11dba4bb5b70732465aff924d29c6564c514c8af362c8322ab0749efd253ff9

...
